using System.Collections;
using System.Collections.Generic;
using System.Linq;
using ApplicationTracker.Data;
using ApplicationTracker.Dtos;
using ApplicationTracker.Models;
using Microsoft.EntityFrameworkCore;

namespace ApplicationTracker.Services
{
    /// <summary>
    /// Database-backed implementation of application CRUD operations
    /// using Entity Framework Core and SQLite.
    /// All operations are asynchronous and use EF Core async APIs.
    /// </summary>
    public class ApplicationService : IApplicationService
    {
        private readonly ApplicationDbContext _db;
        public ApplicationService(ApplicationDbContext db)
        {
            _db = db;
        }

        /// <summary>
        /// Creates a new application and persists it to the database.
        /// The Id is generated by the database.
        /// </summary>
        public async Task<ApplicationModel> Create(ApplicationModel application)
        {
            _db.Applications.Add(application);
            await _db.SaveChangesAsync();
            return application;
        }

        /// <summary>
        /// Returns all stored applications.
        /// </summary>
        public async Task<List<ApplicationModel>> GetAll()
        {
            return await _db.Applications.ToListAsync();
        }

        /// <summary>
        /// Searches applications with optional filters and pagination.
        /// Only applies filters that are actually provided.
        /// </summary>
        public async Task<PagedResult<ApplicationModel>> Search(
        string? status,
        string? company,
        DateOnly? fromDate,
        DateOnly? toDate,
        int page,
        int pageSize)
        {
            var query = _db.Applications.AsQueryable();

            // Guardrails for pagination so weird inputs don't break things.
            page = page < 1 ? 1 : page;
            pageSize = pageSize < 1 ? 10 : pageSize;
            pageSize = pageSize > 100 ? 100 : pageSize;

            // Apply filters only if values were passed in. 
            if (!string.IsNullOrWhiteSpace(status))
            {
                query = query.Where(a => a.Status == status);
            }

            if (!string.IsNullOrWhiteSpace(company))
            {
                query = query.Where(a => a.CompanyName.Contains(company));
            }

            if (fromDate.HasValue)
            {
                query = query.Where(a => a.DateApplied >= fromDate.Value);
            }

            if (toDate.HasValue)
            {
                query = query.Where(a => a.DateApplied <= toDate.Value);
            }

            // Get the total number of matching records before paging
            var totalCount = await query.CountAsync();
            // Order before Skip or Take so pagination stays consistent.
            query = query.OrderByDescending(a => a.DateApplied);

            // Apply pagination at the database level.
            var items = await query.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            // Return the results along with pagination info.
            return new PagedResult<ApplicationModel>
            {
                Items = items,
                TotalCount = totalCount,
                Page = page,
                PageSize = pageSize
            };
        }

        /// <summary>
        /// Retrieves a single application by Id.
        /// Returns null if not found.
        /// </summary>
        public async Task<ApplicationModel?> GetById(int id)
        {
            return await _db.Applications.FirstOrDefaultAsync(a => a.Id == id);
        }

        /// <summary>
        /// Updates an existing application.
        /// Returns true if the application was found and updated,
        /// false if no matching Id exists.
        /// </summary>
        public async Task<bool> Update(int id, ApplicationModel updatedApplication)
        {
            var existing = await _db.Applications.FirstOrDefaultAsync(a => a.Id == id);
            if (existing == null)
                return false;
            
            existing.CompanyName = updatedApplication.CompanyName;
            existing.DateApplied = updatedApplication.DateApplied;
            existing.Status = updatedApplication.Status;
            existing.Notes = updatedApplication.Notes;

            await _db.SaveChangesAsync();
            return true;
        }

        /// <summary>
        /// Deletes an application by Id.
        /// Returns true if deletion occurred,
        /// false if the Id was not found.
        /// </summary>
        public async Task<bool> Delete(int id)
        {
            var existing =  await _db.Applications.FirstOrDefaultAsync(a => a.Id == id);
            if (existing == null)
                return false;

            _db.Applications.Remove(existing);
            await _db.SaveChangesAsync();
            return true;
        }
    }
}
