using System.Collections.Generic;
using System.Linq;
using ApplicationTracker.Models;
using ApplicationTracker.Data;
using Microsoft.EntityFrameworkCore;

namespace ApplicationTracker.Services
{
    /// <summary>
    /// Database-backed implementation of application CRUD operations
    /// using Entity Framework Core and SQLite.
    /// </summary>
    public class ApplicationService : IApplicationService
    {
        private readonly ApplicationDbContext _db;
        public ApplicationService(ApplicationDbContext db)
        {
            _db = db;
        }

        /// <summary>
        /// Creates a new application and persists it to the database.
        /// The Id is generated by the database.
        /// </summary>
        public ApplicationModel Create(ApplicationModel application)
        {
            _db.Applications.Add(application);
            _db.SaveChanges();
            return application;
        }

        /// <summary>
        /// Returns all stored applications.
        /// </summary>
        public List<ApplicationModel> GetAll()
        {
            return _db.Applications.ToList();
        }

        /// <summary>
        /// Retrieves a single application by Id.
        /// Returns null if not found.
        /// </summary>
        public ApplicationModel? GetById(int id)
        {
            return _db.Applications.FirstOrDefault(a => a.Id == id);
        }

        /// <summary>
        /// Updates an existing application.
        /// Returns true if the application was found and updated,
        /// false if no matching Id exists.
        /// </summary>
        public bool Update(int id, ApplicationModel updatedApplication)
        {
            var existing = _db.Applications.FirstOrDefault(a => a.Id == id);
            if (existing == null)
                return false;
            
            existing.CompanyName = updatedApplication.CompanyName;
            existing.DateApplied = updatedApplication.DateApplied;
            existing.Status = updatedApplication.Status;
            existing.Notes = updatedApplication.Notes;

            _db.SaveChanges();
            return true;
        }

        /// <summary>
        /// Deletes an application by Id.
        /// Returns true if deletion occurred,
        /// false if the Id was not found.
        /// </summary>
        public bool Delete(int id)
        {
            var existing = _db.Applications.FirstOrDefault(a => a.Id == id);
            if (existing == null)
                return false;

            _db.Applications.Remove(existing);
            _db.SaveChanges();
            return true;
        }
    }
}
